export interface Location {
    name: string;
    impostorHint: string;
}

export interface Topic {
    id: string;
    name: string;
    description: string;
    locations: Location[];
    emoji: string;
}

export const CACHE_TAG = 'v1.1.3-20251214'; // Cache control tag

export const TOPICS: Topic[] = [
    {
        id: "fantasy",
        name: "Fantasía",
        description: "Lugares mágicos e irreales",
        emoji: "✨",
        locations: [
            { name: "Atlantis", impostorHint: "Algas" },
            { name: "Camelot", impostorHint: "Mesa" },
            { name: "Castillo de Drácula", impostorHint: "Sangre" },
            { name: "Castillo de Hogwarts", impostorHint: "Varita" },
            { name: "Ciudad Gótica", impostorHint: "Murciélago" },
            { name: "El País de las Maravillas", impostorHint: "Sombrero" },
            { name: "El País de Nunca Jamás", impostorHint: "Sombra" },
            { name: "El Olimpo", impostorHint: "Rayo" },
            { name: "Estrella de la Muerte", impostorHint: "Láser" },
            { name: "Fábrica de Chocolate", impostorHint: "Billete" },
            { name: "Fortaleza de la Soledad", impostorHint: "Cristales" },
            { name: "Fondo de Bikini", impostorHint: "Piña" },
            { name: "Hobbiton", impostorHint: "Anillo" },
            { name: "Isla de la Calavera", impostorHint: "Simio" },
            { name: "Jardín del Edén", impostorHint: "Manzana" },
            { name: "La Comarca", impostorHint: "Hierba" },
            { name: "Laboratorio de Dexter", impostorHint: "Botón" },
            { name: "Madriguera de Conejo", impostorHint: "Reloj" },
            { name: "Mansión de los Avengers", impostorHint: "Escudo" },
            { name: "Metrópolis", impostorHint: "Capa" },
            { name: "Minas de Moria", impostorHint: "Balrog" },
            { name: "Montaña de la Perdición", impostorHint: "Lava" },
            { name: "Mordor", impostorHint: "Ojo" },
            { name: "Narnia", impostorHint: "León" },
            { name: "Nave Espacial", impostorHint: "Gravedad" },
            { name: "Palacio de Jabba", impostorHint: "Carbonita" },
            { name: "Pandora", impostorHint: "Avatar" },
            { name: "Parque Jurásico", impostorHint: "Ámbar" },
            { name: "Pueblo Paleta", impostorHint: "Pokebola" },
            { name: "Reino Champiñón", impostorHint: "Estrella" },
            { name: "Rivendel", impostorHint: "Elfo" },
            { name: "Taller de Santa", impostorHint: "Reno" },
            { name: "Springfield", impostorHint: "Rosquilla" },
            { name: "Tardis", impostorHint: "Policía" },
            { name: "Tierra Media", impostorHint: "Mapa" },
            { name: "Torre de los Vengadores", impostorHint: "Ironman" },
            { name: "Valhalla", impostorHint: "Hidromiel" },
            { name: "Wakanda", impostorHint: "Vibranium" },
            { name: "Westeros", impostorHint: "Trono" },
            { name: "Winterfell", impostorHint: "Lobo" }
        ]
    },
    {
        id: "food",
        name: "Comida",
        description: "Gastronomía y lugares de comer",
        emoji: "🍔",
        locations: [
            { name: "Asador", impostorHint: "Carne" },
            { name: "Bar de Tapas", impostorHint: "Aceituna" },
            { name: "Barbacoa", impostorHint: "Carbón" },
            { name: "Bistró", impostorHint: "Vino" },
            { name: "Bodega de Vinos", impostorHint: "Corcho" },
            { name: "Buffet Libre", impostorHint: "Bandeja" },
            { name: "Cafetería", impostorHint: "Taza" },
            { name: "Cantina", impostorHint: "Tequila" },
            { name: "Carrito de Hot Dogs", impostorHint: "Mostaza" },
            { name: "Casa de Té", impostorHint: "Infusión" },
            { name: "Cervecería", impostorHint: "Lúpulo" },
            { name: "Chocolatería", impostorHint: "Bombón" },
            { name: "Cocina", impostorHint: "Sartén" },
            { name: "Comedor Escolar", impostorHint: "Bandeja" },
            { name: "Confitería", impostorHint: "Azúcar" },
            { name: "Crepería", impostorHint: "Masa" },
            { name: "Despensa", impostorHint: "Lata" },
            { name: "Donutería", impostorHint: "Glaseado" },
            { name: "Dulcería", impostorHint: "Caramelo" },
            { name: "Fábrica de Dulces", impostorHint: "Olla" },
            { name: "Food Truck", impostorHint: "Camión" },
            { name: "Frutería", impostorHint: "Manzana" },
            { name: "Hamburguesería", impostorHint: "Queso" },
            { name: "Heladería", impostorHint: "Cono" },
            { name: "Huerto", impostorHint: "Tierra" },
            { name: "Mercado", impostorHint: "Bolsa" },
            { name: "Panadería", impostorHint: "Harina" },
            { name: "Parrilla", impostorHint: "Fuego" },
            { name: "Pastelería", impostorHint: "Crema" },
            { name: "Pizzería", impostorHint: "Masa" },
            { name: "Pollería", impostorHint: "Huevo" },
            { name: "Puesto de Tacos", impostorHint: "Salsa" },
            { name: "Quesería", impostorHint: "Leche" },
            { name: "Restaurante Chino", impostorHint: "Palillos" },
            { name: "Restaurante de Lujo", impostorHint: "Mantel" },
            { name: "Restaurante Italiano", impostorHint: "Pasta" },
            { name: "Restaurante Japonés", impostorHint: "Sushi" },
            { name: "Rotisería", impostorHint: "Pollo" },
            { name: "Sandwichería", impostorHint: "Miga" },
            { name: "Supermercado", impostorHint: "Caja" },
            { name: "Tienda de Conveniencia", impostorHint: "Snack" },
            { name: "Vinoteca", impostorHint: "Copa" }
        ]
    },
    {
        id: "general",
        name: "General",
        description: "Lugares comunes y cotidianos",
        emoji: "🌍",
        locations: [
            { name: "Aeropuerto", impostorHint: "Fuselaje" },
            { name: "Ascensor", impostorHint: "Botones" },
            { name: "Autolavado", impostorHint: "Espuma" },
            { name: "Banco", impostorHint: "Bóveda" },
            { name: "Biblioteca", impostorHint: "Silencio" },
            { name: "Bodega", impostorHint: "Cajas" },
            { name: "Cafetería", impostorHint: "Granos" },
            { name: "Calle", impostorHint: "Semáforo" },
            { name: "Campo de Golf", impostorHint: "Hoyo" },
            { name: "Cárcel", impostorHint: "Rejas" },
            { name: "Carnaval", impostorHint: "Mascara" },
            { name: "Casa", impostorHint: "Llaves" },
            { name: "Cementerio", impostorHint: "Lápida" },
            { name: "Centro Comercial", impostorHint: "Vitrina" },
            { name: "Cine", impostorHint: "Butaca" },
            { name: "Circo", impostorHint: "Carpa" },
            { name: "Cocina", impostorHint: "Horno" },
            { name: "Concierto", impostorHint: "Bafles" },
            { name: "Crucero", impostorHint: "Cubierta" },
            { name: "Escuela", impostorHint: "Pizarra" },
            { name: "Estación de Bomberos", impostorHint: "Sirena" },
            { name: "Estación de Policía", impostorHint: "Placa" },
            { name: "Estación de Tren", impostorHint: "Rieles" },
            { name: "Estadio", impostorHint: "Tribuna" },
            { name: "Farmacia", impostorHint: "Receta" },
            { name: "Ferretería", impostorHint: "Tornillo" },
            { name: "Gimnasio", impostorHint: "Mancuerna" },
            { name: "Hospital", impostorHint: "Camilla" },
            { name: "Hotel", impostorHint: "Recepción" },
            { name: "Iglesia", impostorHint: "Altar" },
            { name: "Jardín", impostorHint: "Riego" },
            { name: "Laboratorio", impostorHint: "Microscopio" },
            { name: "Lavandería", impostorHint: "Detergente" },
            { name: "Librería", impostorHint: "Estante" },
            { name: "Mercado", impostorHint: "Báscula" },
            { name: "Museo", impostorHint: "Vitrina" },
            { name: "Oficina", impostorHint: "Teclado" },
            { name: "Parque", impostorHint: "Banco" },
            { name: "Playa", impostorHint: "Arena" },
            { name: "Peluquería", impostorHint: "Tijeras" },
            { name: "Piscina", impostorHint: "Cloro" },
            { name: "Restaurante", impostorHint: "Menú" },
            { name: "Sauna", impostorHint: "Vapor" },
            { name: "Spa", impostorHint: "Masaje" },
            { name: "Supermercado", impostorHint: "Carrito" },
            { name: "Teatro", impostorHint: "Telón" },
            { name: "Tienda", impostorHint: "Caja" },
            { name: "Universidad", impostorHint: "Campus" },
            { name: "Zoológico", impostorHint: "Jaula" },
            { name: "Discoteca", impostorHint: "Bola" }
        ]
    },
    {
        id: "geography",
        name: "Geografía",
        description: "Lugares del mundo",
        emoji: "🗺️",
        locations: [
            { name: "Amazonas", impostorHint: "Piraña" },
            { name: "Antártida", impostorHint: "Pingüino" },
            { name: "Alpes", impostorHint: "Esquí" },
            { name: "Atacama", impostorHint: "Sal" },
            { name: "Bali", impostorHint: "Templo" },
            { name: "Bora Bora", impostorHint: "Bungalow" },
            { name: "Cañón del Colorado", impostorHint: "Roca" },
            { name: "Caribe", impostorHint: "Palmera" },
            { name: "Cataratas del Iguazú", impostorHint: "Coatí" },
            { name: "Cataratas del Niágara", impostorHint: "Barril" },
            { name: "Copacabana", impostorHint: "Calçadão" },
            { name: "Cordillera de los Andes", impostorHint: "Cóndor" },
            { name: "Desierto de Gobi", impostorHint: "Camello" },
            { name: "Desierto del Sahara", impostorHint: "Duna" },
            { name: "Everest", impostorHint: "Oxígeno" },
            { name: "Galápagos", impostorHint: "Tortuga" },
            { name: "Gran Barrera de Coral", impostorHint: "Arrecife" },
            { name: "Groenlandia", impostorHint: "Iceberg" },
            { name: "Hawaii", impostorHint: "Ukelele" },
            { name: "Himalaya", impostorHint: "Sherpa" },
            { name: "Ibiza", impostorHint: "DJ" },
            { name: "Isla de Pascua", impostorHint: "Moai" },
            { name: "Kilimanjaro", impostorHint: "Nieve" },
            { name: "Las Vegas", impostorHint: "Ficha" },
            { name: "Machu Picchu", impostorHint: "Llama" },
            { name: "Madagascar", impostorHint: "Lemur" },
            { name: "Maldivas", impostorHint: "Atolón" },
            { name: "Mar Muerto", impostorHint: "Salinidad" },
            { name: "Monte Fuji", impostorHint: "Cerezo" },
            { name: "Muralla China", impostorHint: "Ladrillo" },
            { name: "Nilo", impostorHint: "Cocodrilo" },
            { name: "Polo Norte", impostorHint: "Brújula" },
            { name: "Polo Sur", impostorHint: "Base" },
            { name: "Río de Janeiro", impostorHint: "Samba" },
            { name: "Santorini", impostorHint: "Cúpula" },
            { name: "Selva Negra", impostorHint: "Reloj" },
            { name: "Stonehenge", impostorHint: "Monolito" },
            { name: "Tahití", impostorHint: "Collar" },
            { name: "Tíbet", impostorHint: "Yack" },
            { name: "Yellowstone", impostorHint: "Géiser" }
        ]
    },
    {
        id: "history",
        name: "Historia",
        description: "Lugares y eventos históricos",
        emoji: "📜",
        locations: [
            { name: "1492", impostorHint: "Carabela" },
            { name: "Álamo", impostorHint: "Fuerte" },
            { name: "Antigua Grecia", impostorHint: "Toga" },
            { name: "Antigua Roma", impostorHint: "Gladiador" },
            { name: "Bastilla", impostorHint: "Prisión" },
            { name: "Batalla de Waterloo", impostorHint: "Cañón" },
            { name: "Berlín 1989", impostorHint: "Muro" },
            { name: "Caballo de Troya", impostorHint: "Madera" },
            { name: "Castillo Medieval", impostorHint: "Puente" },
            { name: "Chichén Itzá", impostorHint: "Calendario" },
            { name: "Coliseo Romano", impostorHint: "León" },
            { name: "Cruzadas", impostorHint: "Cruz" },
            { name: "Descubrimiento de América", impostorHint: "Mapa" },
            { name: "Día D", impostorHint: "Playa" },
            { name: "Edad de Hielo", impostorHint: "Mamut" },
            { name: "Edad de Piedra", impostorHint: "Silex" },
            { name: "Edad Media", impostorHint: "Peste" },
            { name: "Egipto Antiguo", impostorHint: "Papiro" },
            { name: "El Dorado", impostorHint: "Oro" },
            { name: "Era Vikinga", impostorHint: "Drakkar" },
            { name: "Feria Mundial", impostorHint: "Torre" },
            { name: "Fiebre del Oro", impostorHint: "Pepita" },
            { name: "Guerra Civil", impostorHint: "Mosquete" },
            { name: "Guerra Fría", impostorHint: "Espía" },
            { name: "Guerra de Vietnam", impostorHint: "Helicóptero" },
            { name: "Guillotina", impostorHint: "Cesta" },
            { name: "Imperio Azteca", impostorHint: "Plumas" },
            { name: "Imperio Inca", impostorHint: "Quipu" },
            { name: "Imperio Maya", impostorHint: "Jade" },
            { name: "Industrialización", impostorHint: "Carbón" },
            { name: "Inquisición", impostorHint: "Hoguera" },
            { name: "Misión Apollo 11", impostorHint: "Huella" },
            { name: "Muro de Berlín", impostorHint: "Grafiti" },
            { name: "Partenón", impostorHint: "Columna" },
            { name: "Pearl Harbor", impostorHint: "Radar" },
            { name: "Pirámides de Giza", impostorHint: "Esfinge" },
            { name: "Renacimiento", impostorHint: "Pincel" },
            { name: "Revolución Francesa", impostorHint: "Escarapela" },
            { name: "Revolución Industrial", impostorHint: "Vapor" },
            { name: "Titanic", impostorHint: "Violín" },
            { name: "Wild West", impostorHint: "Revólver" }
        ]
    },
    {
        id: "institutions",
        name: "Instituciones",
        description: "Organizaciones y edificios oficiales",
        emoji: "🏛️",
        locations: [
            { name: "Academia Militar", impostorHint: "Desfile" },
            { name: "Asilo", impostorHint: "Bastón" },
            { name: "Banco Central", impostorHint: "Reserva" },
            { name: "Biblioteca Nacional", impostorHint: "Archivo" },
            { name: "Bolsa de Valores", impostorHint: "Campana" },
            { name: "Bomberos", impostorHint: "Manguera" },
            { name: "Cámara de Comercio", impostorHint: "Reunión" },
            { name: "Capitolio", impostorHint: "Cúpula" },
            { name: "Cárcel Federal", impostorHint: "Uniforme" },
            { name: "Casa Blanca", impostorHint: "Despacho" },
            { name: "Catedral", impostorHint: "Vitral" },
            { name: "Centro de Investigación", impostorHint: "Bata" },
            { name: "Centro de Rehabilitación", impostorHint: "Terapia" },
            { name: "Clínica", impostorHint: "Jeringa" },
            { name: "Comisaría", impostorHint: "Calabozo" },
            { name: "Congreso", impostorHint: "Estrado" },
            { name: "Consulado", impostorHint: "Visado" },
            { name: "Corte Suprema", impostorHint: "Mazo" },
            { name: "Cruz Roja", impostorHint: "Sangre" },
            { name: "Estación Espacial", impostorHint: "Módulo" },
            { name: "Embajada", impostorHint: "Bandera" },
            { name: "Escuela de Derecho", impostorHint: "Código" },
            { name: "Escuela de Medicina", impostorHint: "Anatomía" },
            { name: "Facultad", impostorHint: "Aula" },
            { name: "Fundación", impostorHint: "Donación" },
            { name: "Hospital General", impostorHint: "Urgencias" },
            { name: "Juzgado", impostorHint: "Estrado" },
            { name: "Laboratorio Nacional", impostorHint: "Pipeta" },
            { name: "Ministerio", impostorHint: "Sello" },
            { name: "Municipalidad", impostorHint: "Trámite" },
            { name: "Museo Nacional", impostorHint: "Colección" },
            { name: "Observatorio", impostorHint: "Telescopio" },
            { name: "ONU", impostorHint: "Cascos" },
            { name: "Orfanato", impostorHint: "Litera" },
            { name: "Palacio de Gobierno", impostorHint: "Balcón" },
            { name: "Parlamento", impostorHint: "Debate" },
            { name: "Penitenciaría", impostorHint: "Torre" },
            { name: "Pentágono", impostorHint: "Seguridad" },
            { name: "Sede de Gobierno", impostorHint: "Protocolo" },
            { name: "Universidad Estatal", impostorHint: "Tesis" }
        ]
    },
    {
        id: "professions",
        name: "Profesiones",
        description: "Lugares de trabajo",
        emoji: "💼",
        locations: [
            { name: "Agencia de Publicidad", impostorHint: "Brief" },
            { name: "Aserradero", impostorHint: "Tronco" },
            { name: "Astillero", impostorHint: "Casco" },
            { name: "Barbería", impostorHint: "Navaja" },
            { name: "Bufete de Abogados", impostorHint: "Demanda" },
            { name: "Cantera", impostorHint: "Dinamita" },
            { name: "Carpintería", impostorHint: "Cepillo" },
            { name: "Central Eléctrica", impostorHint: "Turbina" },
            { name: "Clínica Dental", impostorHint: "Torno" },
            { name: "Clínica Veterinaria", impostorHint: "Correa" },
            { name: "Cocina de Chef", impostorHint: "Gorro" },
            { name: "Compañía de Seguros", impostorHint: "Póliza" },
            { name: "Consultorio", impostorHint: "Recetario" },
            { name: "Despacho", impostorHint: "Sillón" },
            { name: "Editorial", impostorHint: "Manuscrito" },
            { name: "Estudio de Arquitectura", impostorHint: "Maqueta" },
            { name: "Estudio de Arte", impostorHint: "Caballete" },
            { name: "Estudio de Grabación", impostorHint: "Consola" },
            { name: "Estudio de TV", impostorHint: "Foco" },
            { name: "Fábrica", impostorHint: "Cinta" },
            { name: "Granja Industrial", impostorHint: "Silo" },
            { name: "Imprenta", impostorHint: "Rodillo" },
            { name: "Laboratorio Químico", impostorHint: "Matraz" },
            { name: "Lavandería Industrial", impostorHint: "Secadora" },
            { name: "Mina", impostorHint: "Pico" },
            { name: "Taller de Costura", impostorHint: "Maniquí" },
            { name: "Obra de Construcción", impostorHint: "Grúa" },
            { name: "Oficina de Correos", impostorHint: "Estampilla" },
            { name: "Oficina de Diseño", impostorHint: "Pantone" },
            { name: "Panadería", impostorHint: "Harina" },
            { name: "Pastelería", impostorHint: "Manga" },
            { name: "Barco Pesquero", impostorHint: "Red" },
            { name: "Plataforma Petrolífera", impostorHint: "Barril" },
            { name: "Quirófano", impostorHint: "Bisturí" },
            { name: "Estación de Radio", impostorHint: "Antena" },
            { name: "Redacción de Periódico", impostorHint: "Titular" },
            { name: "Sala de Juntas", impostorHint: "Proyector" },
            { name: "Sastrería", impostorHint: "Metro" },
            { name: "Taller Mecánico", impostorHint: "Gata" },
            { name: "Torre de Control", impostorHint: "Radar" }
        ]
    },
    {
        id: "romance",
        name: "Romance",
        description: "Lugares románticos",
        emoji: "❤️",
        locations: [
            { name: "Balcón", impostorHint: "Serenata" },
            { name: "Banquete de Boda", impostorHint: "Torta" },
            { name: "Baño de Espuma", impostorHint: "Burbujas" },
            { name: "Cabaña en el Bosque", impostorHint: "Chimenea" },
            { name: "Cama", impostorHint: "Almohada" },
            { name: "Campo de Flores", impostorHint: "Margarita" },
            { name: "Cena a la Luz de las Velas", impostorHint: "Candelabro" },
            { name: "Cine Drive-in", impostorHint: "Auto" },
            { name: "Cita a Ciegas", impostorHint: "Misterio" },
            { name: "Crucero al Atardecer", impostorHint: "Popa" },
            { name: "Despedida de Soltera", impostorHint: "Banda" },
            { name: "Día de San Valentín", impostorHint: "Cupido" },
            { name: "Escapada de Fin de Semana", impostorHint: "Maleta" },
            { name: "Fuegos Artificiales", impostorHint: "Pólvora" },
            { name: "Góndola Veneciana", impostorHint: "Remo" },
            { name: "Jacuzzi", impostorHint: "Chorro" },
            { name: "Jardín de Rosas", impostorHint: "Espina" },
            { name: "Joyería", impostorHint: "Diamante" },
            { name: "Lago de los Cisnes", impostorHint: "Bote" },
            { name: "Luna de Miel", impostorHint: "Hotel" },
            { name: "Muelle", impostorHint: "Pesca" },
            { name: "Noche de Bodas", impostorHint: "Lencería" },
            { name: "Noria", impostorHint: "Altura" },
            { name: "Parque al Atardecer", impostorHint: "Banco" },
            { name: "Paseo en Carruaje", impostorHint: "Caballo" },
            { name: "Picnic", impostorHint: "Mantel" },
            { name: "Playa Privada", impostorHint: "Sombrilla" },
            { name: "Propuesta de Matrimonio", impostorHint: "Rodilla" },
            { name: "Puente de los Candados", impostorHint: "Llave" },
            { name: "Restaurante de Lujo", impostorHint: "Cuenta" },
            { name: "Rooftop Bar", impostorHint: "Cóctel" },
            { name: "Sala de Baile", impostorHint: "Vals" },
            { name: "San Valentín", impostorHint: "Tarjeta" },
            { name: "Spa para Parejas", impostorHint: "Aceite" },
            { name: "Suite Nupcial", impostorHint: "Champán" },
            { name: "Terraza", impostorHint: "Viento" },
            { name: "Tienda de Lenceria", impostorHint: "Encaje" },
            { name: "Tienda de Novias", impostorHint: "Velo" },
            { name: "Tarde de Lluvia", impostorHint: "Paraguas" },
            { name: "Viñedo", impostorHint: "Copa" }
        ]
    },
    {
        id: "zoology",
        name: "Zoología",
        description: "Reino animal y hábitats",
        emoji: "🦁",
        locations: [
            { name: "Acuario", impostorHint: "Vidrio" },
            { name: "Arrecife de Coral", impostorHint: "Buzo" },
            { name: "Aviario", impostorHint: "Malla" },
            { name: "Bosque de Bambú", impostorHint: "Panda" },
            { name: "Bosque Tropical", impostorHint: "Humedad" },
            { name: "Cascada", impostorHint: "Rocío" },
            { name: "Charca", impostorHint: "Rana" },
            { name: "Colmena", impostorHint: "Miel" },
            { name: "Corral", impostorHint: "Barro" },
            { name: "Cueva", impostorHint: "Murciélago" },
            { name: "Delta", impostorHint: "Sedimento" },
            { name: "Desierto", impostorHint: "Cactus" },
            { name: "Establo", impostorHint: "Paja" },
            { name: "Estanque", impostorHint: "Lirio" },
            { name: "Golfo", impostorHint: "Costa" },
            { name: "Granja", impostorHint: "Tractor" },
            { name: "Hormiguero", impostorHint: "Túnel" },
            { name: "Isla Desierta", impostorHint: "Coco" },
            { name: "Lago", impostorHint: "Canoa" },
            { name: "Madriguera", impostorHint: "Topo" },
            { name: "Manglar", impostorHint: "Raíz" },
            { name: "Mar Abierto", impostorHint: "Ola" },
            { name: "Marisma", impostorHint: "Junco" },
            { name: "Monte", impostorHint: "Cabra" },
            { name: "Nido", impostorHint: "Rama" },
            { name: "Océano Profundo", impostorHint: "Presión" },
            { name: "Pantano", impostorHint: "Caimán" },
            { name: "Parque Nacional", impostorHint: "Guardaparque" },
            { name: "Pastizal", impostorHint: "Vaca" },
            { name: "Pecera", impostorHint: "Filtro" },
            { name: "Perrera", impostorHint: "Jaula" },
            { name: "Polo", impostorHint: "Hielo" },
            { name: "Pradera", impostorHint: "Bisonte" },
            { name: "Refugio de Vida Silvestre", impostorHint: "Binoculares" },
            { name: "Reserva Natural", impostorHint: "Sendero" },
            { name: "Río", impostorHint: "Piedra" },
            { name: "Sabana", impostorHint: "León" },
            { name: "Selva", impostorHint: "Liana" },
            { name: "Tundra", impostorHint: "Musgo" },
            { name: "Veterinaria", impostorHint: "Vacuna" }
        ]
    }
];
